version: '3'

services:
  node:
    build:
      context: .
      dockerfile: docker_images/node.Dockerfile
    container_name: node
    depends_on: 
      - postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_HOSTNAME=node
      - NODE_PORT=8080
    ports:
      - "443:8080"
    volumes:
      - ./src:/node/src
    networks:
      - app-network
  
  postgres:
    build:
      context: .
      dockerfile: docker_images/postgres.Dockerfile
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=$PG_DB
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
    ports:
      - "5432:5432"
    volumes:  
      - data:/postgres/data
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    depends_on: 
      - postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment: 
      - PGADMIN_DEFAULT_EMAIL=$PGA_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGA_PASSWORD
    ports:
      - "8081:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  data:
