version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: node.Dockerfile
    image: node:lts-alpine
    container_name: node
    depends_on: 
      - postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_HOSTNAME=node
      - NODE_PORT=8080
    ports:
      - "443:8080"
    volumes:
      - ./src:/srv/app/src
    networks:
      - app-network
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
    ports:
      - "5432:5432"
    volumes:  
      - data:/srv/app/data/postgres
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pdAdmin
    depends_on: 
      - postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment: 
      - PGADMIN_DEFAULT_EMAIL=$PGA_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGA_PASSWORD
    ports:
      - "8081:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  data: